HOURS = 'часов'
MINUTES = 'минут'
START_TIME = 'Введите начальное время отбытия Перри Утконоса: '
TIME_IN_MINUTES = 'Время в минутах'
TIME_IN_HOURS = 'Время в часах'
FINISH_TIME = 'Агент Пи справился за'
